### ISSUE TITLE
抽水的矿工名经常掉线

### ISSUE THREAD

**Issue by 910610915** [CaoCaoMiner/CC-Miner-Tax-Proxy#2]
你好，抽水的矿工名经常掉线，得老半天才会上线，显示的算力和设置的抽水算力也不一样，这是咋回事呢？

**Comment by CaoCaoMiner** [comment]
接入总算力小，那么你不是时时刻刻抽水，15分钟没抽到肯定掉线
显示的算力是矿机的算力，你要关心的是24小时平均算力和你接入矿机总算力的比值是否等于你的抽水比例
